version: "3.8"

services:

  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - SIGNUPS_ALLOWED=true
    volumes:
      - bitwarden_data:/data/
    ports:
      - 91:80/tcp #WebUI port
    restart: unless-stopped
    networks:
      - frontend

volumes:
  bitwarden_data:

networks:
  frontend:
    external: true