version: "3.8"

services:

  deemix:
    container_name: deemix
    image: registry.gitlab.com/bockiii/deemix-docker:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - ARL=<token>
      - UMASK_SET=022 #rwxr-xr-x
    volumes:
      - /srv/nfs/media/deemix/downloads:/downloads
      - deemix_config:/config
    ports:
      - 6595:6595
    restart: unless-stopped
    networks:
      - frontend

volumes:
  deemix_config:

networks:
  frontend:
    external: true