version: "3.8"

services:

  diun:
    container_name: diun
    image: crazymax/diun:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    command: serve
    environment:
      - TZ=Europe/Paris
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 06 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_REGOPTS_0_NAME=docker.io
      - DIUN_REGOPTS_0_SELECTOR=image
      - DIUN_REGOPTS_0_USERNAME=<docker_hub_username>
      - DIUN_REGOPTS_0_PASSWORD=<docker_hub_password>
    volumes:
      - diun_data:/data
      - diun:/etc/diun
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - frontend

volumes:
  diun_data:
  diun:

networks:
  frontend:
    external: true