version: "3.8"

services:
  mariadb-10.5:
    container_name: mariadb-photoview
    image: mariadb:10.5
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - mariadb-photoview:/var/lib/mysql
    networks:
      - backend

  photoview:
    container_name: photoview
    image: viktorstrate/photoview
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 8080:80
    depends_on:
      - mariadb-10.5
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(mariadb-10.5)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
    volumes:
      - photoview_api_cache:/app/cache
      - /srv/nfs/media/photos:/photos:ro
    networks:
      - frontend
      - backend

volumes:
  mariadb-photoview:
  photoview_api_cache:

networks:
  frontend:
    external: true
  backend:
    external: true