version: "3.8"

services:

  podgrab:
    container_name: podgrab
    image: akhilrex/podgrab:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - CHECK_FREQUENCY=30 # Fréquence de rafraichissement en min
      - PASSWORD=<password> # Optionel, le username = podgrab
    volumes:
      - podgrab_config:/config
      - /srv/nfs/media/podgrab:/assets
    ports:
      - 7080:8080 # Modifier à 7080 car mon port 8080 est déjà utilisé
    restart: unless-stopped
    networks:
      - frontend

volumes:
  podgrab_config:

networks:
  frontend:
    external: true