version: "3.8"

services:
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - TZ=Europe/Paris
    volumes:
      - nfs_config:/config
    ports:
      - 5080:80
      - 5443:443
    restart: unless-stopped
    networks:
      - frontend

volumes:
  nfs_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas-hp.home,rw,soft,nfsvers=4
      device: ":/srv/raid/nfs/docker/heimdall_nfs_config"

networks:
  frontend:
    external: true