version: "3.8"

services:

  teslamate:
    image: teslamate/teslamate:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - ENCRYPTION_KEY= #insert a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto 
    volumes:
      - nfs_import:/opt/app/import
    ports:
      - 4000:4000
    restart: unless-stopped
    cap_drop:
      - all
    networks:
      - frontend
      - backend

  database:
    image: postgres:13
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  grafana:
    image: teslamate/grafana:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    volumes:
      - nfs_grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - frontend
      - backend

  mosquitto:
    image: eclipse-mosquitto:1.6
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - nfs_mosquitto-conf:/mosquitto/config
      - nfs_mosquitto-data:/mosquitto/data
      - nfs_mosquitto-log:/mosquitto/log
    ports:
      - 1883:1883
    restart: unless-stopped
    networks:
      - frontend
      - backend

volumes:
  db:
  nfs_import:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas-hp.home,rw,soft,nfsvers=4
      device: ":/srv/raid/nfs/docker/teslamate_nfs_import"
  nfs_grafana-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas-hp.home,rw,soft,nfsvers=4
      device: ":/srv/raid/nfs/docker/teslamate_nfs_grafana-data"
  nfs_mosquitto-conf:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas-hp.home,rw,soft,nfsvers=4
      device: ":/srv/raid/nfs/docker/teslamate_nfs_mosquitto-conf"
  nfs_mosquitto-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas-hp.home,rw,soft,nfsvers=4
      device: ":/srv/raid/nfs/docker/teslamate_nfs_mosquitto-data"
  nfs_mosquitto-log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas-hp.home,rw,soft,nfsvers=4
      device: ":/srv/no-raid/nfs1/docker/teslamate_nfs_mosquitto-log"

networks:
  frontend:
    external: true
  backend:
    external: true
